version: "3.8"
services:
  app:
    build:
        context: .
        # pass VERSION into the build (falls back to “latest” if not set in your shell/.env)
        args:
          VERSION: "${VERSION:-latest}"
    ports:
      - "5000:5000"
    env_file:
      - .env
